# configs/model_config.yaml
model_params:
  lstm:
    units: [100, 100, 50]
    dropout: 0.2
    learning_rate: 0.001
    epochs: 100
    batch_size: 32
  
  cnn_lstm:
    filters: [64, 32]
    kernel_size: 3
    lstm_units: 100
    dropout: 0.2
    epochs: 100
  
  random_forest:
    n_estimators: 200
    max_depth: 20
    random_state: 42
  
  xgboost:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 10

feature_engineering:
  lookback_window: 60
  forecast_horizon: 7
  technical_indicators:
    - sma_20
    - sma_50
    - ema_12
    - ema_26
    - macd
    - rsi_14
    - bollinger_bands
    - atr_14
    - obv
